platform :ios, '9.2'
use_frameworks!

pod 'React', :path => './ReactComponents/node_modules/react-native', :subspecs => [
  'Core',
  'RCTImage',
  'RCTNetwork',
  'RCTText',
  'RCTWebSocket',
  # Add any other subspecs you want to use in your project
]
